const fs=require('fs');
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,AlignmentType,HeadingLevel,
    BorderStyle,WidthType,ShadingType,PageNumber,Footer,LevelFormat,ImageRun}=require('docx');
const F="Arial";
const H1=t=>new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun(t)]});
const H2=t=>new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun(t)]});
const P=(t,j=true)=>new Paragraph({spacing:{after:120},alignment:j?AlignmentType.JUSTIFIED:AlignmentType.LEFT,
 children:Array.isArray(t)?t:[new TextRun(t)]});
const B=t=>new TextRun({text:t,bold:true});
const I=t=>new TextRun({text:t,italics:true});
const T=t=>new TextRun(t);
const M=t=>new TextRun({text:t,font:"Consolas"});
const BUL=t=>new Paragraph({numbering:{reference:"bul",level:0},spacing:{after:60},children:Array.isArray(t)?t:[new TextRun(t)]});
const NUM=t=>new Paragraph({numbering:{reference:"num",level:0},spacing:{after:80},children:Array.isArray(t)?t:[new TextRun(t)]});
const REF=t=>new Paragraph({spacing:{after:60},indent:{left:480,hanging:480},children:[new TextRun({text:t,size:19})]});
const bd={style:BorderStyle.SINGLE,size:1,color:"BBBBBB"};const bds={top:bd,bottom:bd,left:bd,right:bd};
const cell=(x,w,h)=>new TableCell({borders:bds,width:{size:w,type:WidthType.DXA},
 shading:h?{fill:"D6E4F0",type:ShadingType.CLEAR}:undefined,margins:{top:60,bottom:60,left:100,right:100},
 children:[new Paragraph({children:[new TextRun({text:x,bold:!!h,size:19})]})]});
const table=(w,rows)=>new Table({width:{size:w.reduce((a,b)=>a+b,0),type:WidthType.DXA},columnWidths:w,
 rows:rows.map((r,ri)=>new TableRow({children:r.map((c,ci)=>cell(c,w[ci],ri===0))}))});
const cap=t=>new Paragraph({spacing:{after:80},children:[B(t)]});
const sp=()=>new Paragraph({spacing:{before:80}});
const figP=(file,w,h)=>new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:140,after:140},
 children:[new ImageRun({type:"png",data:fs.readFileSync("figures/"+file),transformation:{width:w,height:h},
 altText:{title:file,description:file,name:file}})]});

const kids=[
 new Paragraph({style:"Title",children:[new TextRun("Leakage-Safe Evaluation of Quantum Transpiler Regression Testing")]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:120},children:[new TextRun({text:"Oracle Observability, Metadata Faults, and a Cost-Aware Pilot in Qiskit",italics:true,size:24})]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:30},children:[new TextRun({text:"Furqan Nasir¹,², Arif Shah¹, Iftikhar Alam¹",size:24})]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:14},children:[new TextRun({text:"¹ City University of Science and Information Technology (CUSIT), Peshawar, Pakistan (PhD Student, Computer Science)",size:19})]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:14},children:[new TextRun({text:"² Department of Computer Science, National University of Computer and Emerging Sciences (FAST-NUCES), Islamabad, Pakistan (Lecturer)",size:19})]}),
 new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:200},children:[new TextRun({text:"Corresponding author: Furqan Nasir (furqannr@gmail.com) · ORCID: Furqan Nasir 0000-0002-5259-3448, Arif Shah 0000-0003-0090-3333",size:19})]}),

 H1("Abstract"),
 P([T("A quantum compiler such as Qiskit’s transpiler changes frequently, and a pass modification can cause a correctness, circuit-quality, or performance regression. We study regression-test selection, and our main contribution is a leakage-safe evaluation methodology (cohort separation, provenance control, validity gates) together with a fault-manifestation taxonomy for transpiler regressions. In a Qiskit 2.x pilot over nine controlled mutations and 32 circuit-backend units, a transparent risk-based prototype selector shows no advantage over baselines or random ordering. A mining study of 26 real transpiler fixes finds about 38% lie in channels invisible to output-equivalence oracles, which we confirm on one built-from-source regression.")]),
 new Paragraph({spacing:{after:160},children:[B("Keywords: "),T("Quantum software engineering · Quantum transpiler · Regression test selection · Quantum circuit equivalence checking · Qiskit")]}),

 H1("1. Introduction"),
 P([T("Quantum software development kits (SDKs) such as Qiskit are developed at a rapid and continuous pace, and the compilers inside them, the transpilers that map an abstract circuit onto a hardware-native gate set and a limited qubit connectivity, are revised very often. A single change in a layout, routing, translation, optimization, or scheduling pass can introduce a regression of one of three kinds. The first is a correctness regression, in which the program crashes or the compiled circuit computes a different unitary. The second is a circuit-quality regression, in which the output carries more two-qubit gates or a larger depth and therefore loses fidelity on noisy hardware. The third is a compilation-performance regression, in which the transpilation itself becomes slower or consumes more memory. Empirical studies have already shown that compiler and transpiler components are an important source of defects in quantum platforms [1], and several recent Qiskit transpiler fixes fall into exactly these three categories.")]),
 P([T("Detecting such regressions early is, in essence, a regression-testing problem; the real difficulty is that the test space is very large. The atomic unit of testing is a tuple of the form (circuit, backend, transpiler configuration, oracle), and a realistic suite ranges over many circuit families and several device topologies. Existing benchmark suites, for instance, already enumerate on the order of a thousand workloads for a single SDK [2]. Re-executing the complete suite together with its equivalence oracles on every change therefore exhausts any practical CI budget rather quickly.")]),
 P([I("Motivating scenario. "),T("Consider a developer who opens a pull request that modifies a routing heuristic. Most of the suite has nothing to do with this particular change, and yet the tight budget of a pre-merge pipeline permits only a small fraction of the tests to run. The question we ask is therefore the following: which tests, and in which order, give the best chance of revealing a regression introduced by this change, given that the cost of each test, transpilation together with oracle evaluation, varies a great deal from one test to another?")]),
 P([T("For conventional software this question is addressed by classical regression test prioritization, and decades of empirical evidence indicate that simple cost-, history-, and change-aware heuristics are strong baselines, frequently remaining competitive with much heavier learned models when labelled failure data are scarce [3, 4]. To the best of our knowledge, however, no earlier work has formalized or evaluated cost-aware regression test selection for the quantum transpiler in particular, where the faults are compiler regressions and the oracle must reason about circuit equivalence under a permutation of the qubit layout. Most existing quantum-testing research instead aims at finding bugs and generating tests through metamorphic or differential testing [5, 6, 7, 8], or at benchmarking SDKs [2]; this is complementary to our problem but distinct from the budgeted selection of existing tests for an incoming change.")]),
 P([T("This paper contributes a methodology and an honest feasibility pilot, not a large-scale verdict. Concretely:")]),
 NUM([B("A leakage-safe evaluation methodology. "),T("We separate change events into non-pooled cohorts (forward regression, fix-boundary differential, mutation), apply tiered quantum-aware oracles with an empirical false-positive rate, calibrate cost with CPU process time, freeze the change–stage map, and enforce six implementation-validity gates together with a strict claim-scope rule. A fault-manifestation taxonomy classifies each regression by the channel through which it could be detected.")]),
 NUM([B("An oracle-observability analysis. "),T("We show that black-box output-equivalence oracles cannot observe an important class of transpiler regression, namely contract/metadata-channel faults that corrupt internal layout properties while leaving the output unitary intact. We demonstrate this on a built-from-source Qiskit regression (H1) and quantify it through a repository-mining study of 26 real transpiler fixes, of which roughly 38% fall in output-invisible channels.")]),
 NUM([B("A prototype (cart) and an honest feasibility pilot. "),T("The methodology is realized end to end (artifact statement, Section 11) and evaluated on a Qiskit 2.x micro corpus with an audited event ledger. We report a null selection result: a transparent risk_score selector, treated here as a prototype baseline rather than a claimed improvement, does not outperform the simple cost, diversity, history, and change-stage baselines or random ordering at this scale, and an ablation traces the deficit to its severity term. These outcomes motivate the design choices and the pre-specified scale-up.")]),
 P([T("We answer three research questions: RQ1 (is the leakage-safe pipeline operationally sound under an executable gate audit?), RQ2 (how does the transparent selector compare with the baselines (including random ordering) at this scale, and what can be concluded?), and RQ3 (which real historical transpiler regressions are observable through black-box oracles on commodity hardware, and which are merely unreproduced?). All comparative claims are scoped as pilot evidence. Section 2 gives background; Section 3 surveys related work; Section 4 presents the methodology; Section 5 the implementation; Section 6 the pilot; Sections 7–9 discuss findings, threats, and future work; Section 10 concludes; Section 11 is the artifact statement.")]),

 H1("2. Background"),
 H2("2.1 The Qiskit transpiler"),
 P([T("Qiskit compiles an abstract circuit to a target backend through a staged pass manager [9]. The canonical stages are layout, routing, translation, optimization, and scheduling, bundled at optimization levels 0–3. Two properties matter for testing: the actually executed passes depend on the circuit, backend, configuration, and the exact Qiskit revision (so they must be observed, not inferred from source); and transpilation may permute qubits, so a transpiled circuit equals the original only modulo a layout permutation.")]),
 H2("2.2 Transpiler regression types and their manifestation"),
 P([T("We distinguish what kind of defect a regression is from how, and indeed whether, it shows up in an observable signal, because the gap between these two is the central finding of the pilot. The fault-type grouping itself is conventional. The correctness group contains functional faults (a compilation failure) and semantic faults (a different unitary or output). The quality group covers circuit-quality faults, such as a worse two-qubit count or a larger depth. The performance group covers compilation-performance faults. These groupings are not mechanical: a crash is not automatically a semantic fault, and an increase in two-qubit count is not a quality regression if the depth improves substantially. For that reason we judge quality with a Pareto rule over pre-declared thresholds and report the two metrics separately.")]),
 P([T("Crucially, two regressions of the same fault type can manifest in very different observable signals, and some manifest in signals a black-box, output-only oracle never inspects. We therefore use a fault-manifestation taxonomy, the channel through which a regression could be detected:")]),
 cap("Table 1. Study-specific fault-manifestation taxonomy (detection channel)."),
 table([3300,4060,2000],[
  ["Manifestation channel","Observable signal","Output oracle sees it?"],
  ["output_semantic","different unitary/output state","Yes (within oracle width)"],
  ["compilation_failure","crash, exception, invalid circuit","Yes"],
  ["circuit_quality","worse two-qubit count or depth","Yes"],
  ["performance","slower / more memory-hungry compilation","Yes, if over the screen"],
  ["transpiler_contract_or_metadata","wrong internal property (TranspileLayout, final_layout, routing_permutation) with applied output still correct","No, invisible to output oracles"],
  ["determinism_or_reproducibility","output varies across fixed-seed runs, often only under a specific (e.g. noisy) target","Only with a determinism oracle on that target"],
 ]),
 sp(),
 P([T("This taxonomy is what makes the historical results in Section 6.4 interpretable, since a regression can be entirely real and yet sit in a channel that our black-box pipeline never observes. The ElidePermutations regression (H1), for instance, manifests in the transpiler_contract_or_metadata channel: it corrupts a layout property rather than producing a wrong output unitary. The VF2Layout regression (H3) manifests as determinism_or_reproducibility under a noisy target, which is neither a circuit_quality nor an output_semantic signal. In both cases a “pass” from the output oracle is exactly what one should expect, and it is not evidence that the oracle under-detects quality or semantic faults.")]),
 H2("2.3 The oracle problem for transpilation"),
 P([T("Deciding whether a transpiled circuit is correct is an instance of the quantum oracle problem [10], which is the central obstacle catalogued in the general test-oracle survey [11]. When a circuit is small and unitary-pure, one can normalize the transpiled layout and then compare unitaries modulo global phase. This comparison is exact, but it does not scale, because an n-qubit operator already has 2^n × 2^n complex entries. Larger or non-unitary circuits must instead be checked with sampled-statevector, observable, metamorphic, or structural methods [5]. One consequence is central to our findings: a black-box oracle only observes the output, so a fault that corrupts internal metadata while leaving the output unitary intact can remain invisible to it. Dedicated quantum equivalence-checking methods exploit reversibility and simulation to compare a circuit before and after compilation efficiently [12], yet they too reason about the output map and not about a transpiler's internal contracts.")]),
 H2("2.4 Rate-of-detection metrics"),
 P([T("Classically, prioritization is measured by APFD and by its cost-cognizant variant APFDc, which weights detection by cost and severity [13, 14]. APFDc, however, assumes that a single common ordering exposes multiple faults. In our setting each event typically has only one fault, ranked under its own ordering, so APFDc is not appropriate as a headline metric. We therefore rely on per-event detection-curve summaries, averaged across events, with the cohorts reported separately.")]),

 H1("3. Related Work"),
 P([T("We position the work across three threads and close with an explicit comparison.")]),
 H2("3.1 Regression test selection and prioritization"),
 P([T("Rothermel et al. introduced systematic test-case prioritization and the rate-of-fault-detection measure [15], and Elbaum et al. established APFD together with a family of empirical studies [13]. The cost-cognizant variant APFDc later incorporated varying test costs and fault severities [14], and it is the conceptual ancestor of our objective. In their survey, Yoo and Harman observe that change-, history-, and cost-aware heuristics remain persistently strong baselines [3]. The continuous-integration setting reinforces this: lightweight selection and prioritization that avoid coverage instrumentation are markedly more cost-effective [16], a large empirical study of readily available CI and version-control metadata finds that simple, well-known heuristics frequently outperform complex machine-learned models [17], and information-retrieval-based prioritization reports the same pattern, with simple, well-tuned heuristics staying competitive [18]. This accumulated evidence is what leads us to a transparent selector and to a cautious reading of the pilot. Two adaptations are nevertheless required for transpilation. First, the fault is a compiler regression that spans correctness, quality, and performance, rather than a test failure in the program under test. Second, the oracle must decide circuit equivalence modulo qubit-layout permutation. We keep the cost-aware objective and the strong baselines, but we redefine the fault model, the oracles, and the metrics.")]),
 H2("3.2 Learning-based test selection"),
 P([T("At industrial scale, predictive (learned) test selection trains gradient-boosted models on large histories of test outcomes, and it can halve testing cost while keeping most of the failure signal [4]. Such methods are data-hungry, since they presuppose a large labelled corpus of per-test outcomes, and no such corpus yet exists for quantum-transpiler regressions. A broad literature applies reinforcement learning [19], multi-armed bandits for volatile test pools [20], and other learners surveyed systematically [21] to CI test prioritization, and all of them require substantial historical signal, which only reinforces our staged plan. Because simple heuristics are known to stay competitive when labelled data are sparse [3], we propose a transparent selector first and reserve a learned comparison for a later scale-up under identical anti-leakage rules.")]),
 H2("3.3 Quantum software and compiler testing"),
 P([T("Quantum software testing must also contend with the oracle problem [10]. Metamorphic and differential testing are two ways to mitigate it. MorphQ, for example, generates diverse programs and applies quantum-specific metamorphic relations to test Qiskit, and in doing so exposes real bugs [5], while MorphQ++ reproduces and extends metamorphic testing of quantum compilers [6]. Quantum software engineering is by now an established research thread, including within this venue [22], where the transpiler itself is an active optimization target [23]. Several recent frameworks sharpen the picture. QuCheck offers property-based testing of quantum programs in Qiskit, with flexible generators, assertions, and preconditions that are evaluated through mutation analysis [7]. QEMI adapts equivalence-modulo-inputs compiler testing to quantum stacks, generating program variants by removing dead code and uncovering crash and behavioural bugs across Qiskit, Q#, and Cirq [8]. QDiff applies differential testing to quantum software stacks, exploring semantics-preserving variants and filtering circuits by static characteristics to compare Qiskit, Cirq, and Pyquil [24], and QSPE enumerates skeletal program variants with statevector-based validation, reporting 81 Qiskit miscompilations that developers have acknowledged [25]. Concolic testing targets transpiler decision points, parameter thresholds, and layout heuristics, surfacing missed optimizations and semantic deviations in Qiskit passes [26]. A complementary, formal line of work verifies the compiler directly: Giallar provides push-button verification of Qiskit passes, verifying 44 of 56 passes across 13 versions and uncovering three bugs [27]. Static analysis and bug benchmarks round out the landscape, with LintQ detecting quantum-specific defects that general linters miss [28] and Bugs4Q curating real, reproducible Qiskit bugs [29]. Mutation analysis has likewise been adapted to quantum programs in Muskit [30] and QMutPy [31], and a recent roadmap explicitly names transpilation as an under-studied testing target [32]. Empirical studies confirm that compiler and transpiler components are a significant source of defects [1], and Benchpress benchmarks circuit construction, manipulation, and compilation across SDKs [2]. All of these efforts aim at bug finding, test generation, or benchmarking; much like MorphQ, they create or transform programs in order to expose defects, rather than select among an existing budgeted suite. None of them addresses budgeted selection of existing tests for an incoming transpiler change with quantum-aware oracles, cohort-separated events, CPU-time cost calibration, and leakage-safe temporal evaluation. To our knowledge, cost-aware regression test selection for the quantum transpiler has not previously been formalized or piloted.")]),
 H2("3.4 Positioning"),
 P([T("Table 2 contrasts the closest threads along the axes that matter for budgeted CI of a compiler. Within this very collection, Open QBench benchmarks the performance of quantum-computing platforms [33]; our focus is complementary, in that we select and order existing tests for an incoming transpiler change rather than benchmark platforms. The distinguishing combination of our work is the rightmost five columns taken together: a quantum-aware oracle applied to selecting and ordering existing tests under an explicit cost budget, with leakage-safe temporal evaluation and cohort separation. Individually each property appears somewhere in prior work; in combination, for the quantum transpiler, it does not. (● = yes, ◐ = partial, ○ = no/not applicable.)")]),
 cap("Table 2. Positioning relative to prior work."),
 table([2200,2160,1000,1000,1000,1000,1000],[
  ["Approach","Primary goal","QA oracle","Cost-aware","Selects/orders existing","Leakage-safe temporal","Cohort sep."],
  ["Classical RTP/TCP","prioritize tests of a program","○","●","●","◐","○"],
  ["Predictive selection","learned selection at scale","○","●","●","●","○"],
  ["MorphQ / MorphQ++","metamorphic bug finding","●","○","○","○","○"],
  ["QuCheck","property-based testing","●","○","○","○","○"],
  ["QEMI","EMI stack bug finding","●","○","○","○","○"],
  ["QDiff","differential stack bug finding","●","○","○","○","○"],
  ["QSPE","skeletal-program differential testing","●","○","○","○","○"],
  ["Giallar","formal Qiskit-pass verification","●","○","○","○","○"],
  ["Benchpress","SDK compilation benchmarking","◐","○","○","○","○"],
  ["This work","cost-aware test SELECTION for the transpiler","●","●","●","●","●"],
 ]),
 sp(),

 H1("4. Methodology"),
 H2("4.1 Problem formulation"),
 P([T("Given a transpiler change and a fixed per-event budget B, select and order tests to maximize early detection of regressions. Conceptually each test is scored by expected_value ≈ P(regression | change, circuit, backend) × impact ÷ expected_cost, and tests are chosen greedily within B. P(·) is the conceptual target; the proposed selector realizes it with a transparent surrogate (§4.5). The primary evaluation unit is the (event_id, test_id) pair.")]),
 H2("4.2 Change-event model and cohorts"),
 P([T("The unit of the dataset is a change event, not a commit: an event is a tuple (baseline_revision, candidate_revision, change_metadata, fault_id), each carrying a unique fault_id and a fault_type. Every event declares one of three cohorts, and the cohorts are reported separately and never pooled. A forward_regression event pairs the last known-good parent (the baseline) with the regression-inducing commit (the candidate), and it is the only cohort that models the real CI question. A fix_boundary_differential event is used in reverse orientation when the introducing commit has not been traced: it pairs a fix commit (the baseline) with its parent (the candidate), which yields a fault-revealing differential that we never describe as a prediction of an incoming change. A mutation event injects a single controlled fault on a base revision and is used only to fill gaps in fault-type coverage. Throughout, historical events are preferred.")]),
 figP("fig2_cohorts.png",620,214),
 H2("4.3 Test units, manifest, and provenance"),
 P([T("A test unit is a tuple (circuit, backend, transpiler_configuration, oracle). A static manifest stores its metadata, while a separate calibrated profile records the measured baseline cost, the pass stages that actually executed (obtained through instrumentation rather than inferred from filenames), routing observations, and peak memory, keyed by (event_id, baseline_sha, test_id, event_environment_id). Each unit also declares its provenance, one of pre_existing, extracted_from_fix, or synthesized, together with an available_before_candidate flag, and these support the two evaluations described in §4.8.")]),
 H2("4.4 Oracles"),
 P([B("Semantic. "),T("The semantic oracle is tiered by applicability and width. For a small circuit (at most 12 qubits) that is unitary-pure and ancilla-free, it checks exact unitary equivalence modulo global phase after first normalizing the layout. For every other circuit it falls back to structural validity, meaning adherence to the basis and to the coupling map. A full 2^n operator is therefore never materialized for large circuits. This mirrors dedicated quantum equivalence-checking practice, which compares the maps of the pre- and post-compilation circuits and exploits reversibility and simulation to stay tractable [12].")]),
 P([B("Quality. "),T("A Pareto rule over pre-declared thresholds; Δ two-qubit count and Δ depth reported separately; a sensitivity grid is reported and thresholds are fixed before held-out evaluation.")]),
 P([B("Performance. "),T("A two-stage protocol (median-slowdown screen, then robust effect size); exploratory on a laptop, timed with CPU process time.")]),
 P([B("Empirical false-positive rate. "),T("A warning is a false positive only if not upheld by independent confirmation, never merely because an oracle fired.")]),
 H2("4.5 The proposed transparent selector (risk_score)"),
 P([T("The selector introduces no ML and outputs an interpretable score, not a calibrated probability:")]),
 new Paragraph({spacing:{after:120},alignment:AlignmentType.CENTER,children:[M("risk_score = (ε + change_stage_match) × circuit_backend_sensitivity × impact_prior × oracle_confidence ÷ expected_cost × novelty_multiplier")]}),
 figP("fig3_riskscore.png",600,260),
 P([T("Fault severity (impact_prior) and detection confidence (oracle_confidence) enter as separate multiplicands, so a high-impact test that relies on a weaker oracle is not penalized twice. The ε floor, together with a stage-independent exploration reserve of 10–20%, keeps an incomplete change–stage map from driving useful tests to zero, and unknown or framework-wide changes are routed into that reserve. When no prior qualifying events exist, a neutral cold-start fallback applies. The selector sees only pre-execution information: the candidate’s fault_type, runtime, quality, and labels are never inputs.")]),
 cap("Table 3. Frozen risk_score configuration (pre-declared before evaluation)."),
 table([3600,5760],[
  ["Parameter","Value / rule"],
  ["epsilon (change-stage floor)","0.05"],
  ["exploration reserve","15% of budget (admissible range 10–20%)"],
  ["novelty decay (per repeated family×backend)","0.5^count"],
  ["circuit criticality (impact_prior)","GHZ 1.0, QFT 1.5, linear-QAOA 1.3, random-Clifford 1.2"],
  ["oracle_confidence","unitary 1.0, sampled-SV 0.8, property 0.5, structural 0.3"],
  ["oracle cost estimate (s)","unitary 0.05, sampled-SV 0.20, property 0.05, structural 0.01"],
  ["circuit_backend_sensitivity","(1+pressure) × (1+two-qubit density) × (1 + n/30)"],
  ["impact_prior","criticality × (1+pressure) × (1 + prior-failure-rate)"],
  ["cold-start","prior-failure-rate = 0 ⇒ impact factor 1.0"],
  ["tie-breaking / determinism","ties broken by test_id; seed-deterministic ranking"],
 ]),
 sp(),
 H2("4.6 Baselines and budgeted selection"),
 P([T("Five baselines observe the same budget: random, cheapest-first, diversity-only, history-only, and change-stage heuristic [3]. Selection reserves 10–20% of the budget for stage-independent exploration, fills the main allocation greedily by score, ensures ≥ 1 representative per circuit family where the budget permits, never exceeds the budget, and is seed-deterministic.")]),
 P([T("The baselines behave as follows. Random applies a seeded uniform shuffle of the candidate units. Cheapest-first orders them by ascending expected cost. Diversity-only greedily covers (circuit family × backend) combinations in ascending order of cost, and then adds the cheapest remaining units. History-only ranks units by descending prior failure rate, computed only from events strictly before the event date, breaks ties by cost, and reduces to cheapest-first under a cold start. Change-stage prefers units whose declared pass stages include the modified stage, again breaking ties by cost.")]),
 H2("4.7 Metrics"),
 P([T("Per event and averaged, cohorts/sources separated: Recall@budget, normalized TTFR, detection rate at {5,10,20,40}% budget, area under the detection-vs-budget curve, selection overhead, diversity coverage, and the empirical oracle FP rate. APFDc is reported only for the atypical multiple-fault-per-ordering case.")]),
 H2("4.8 Anti-leakage controls"),
 P([T("Four controls enforce leakage safety. The first is a group-level temporal split keyed by split_group_id = base_revision + mutation_family, which sends any group that straddles the cutoff entirely to the test side. The second is provenance-driven: a Primary CI evaluation restricts the candidates to tests that were available before the candidate, whereas post-fix targeted triggers are confined to a Secondary retrospective evaluation. The third freezes the change–stage map before held-out evaluation, and any later refinement is performed on training events only and is versioned. The fourth calibrates cost with CPU process time (time.process_time) and retains wall-clock time only as a secondary reference.")]),
 H2("4.9 Validity gates and claim scope"),
 P([T("Six gates check implementation correctness before any result is reported: budget compliance, reproducibility, absence of leakage, label reproducibility from the write-once artifacts, metric correctness against hand-computed cases, and oracle coverage. A claim-scope rule then forbids any headline temporal-generalization claim while fewer than three forward_regression events are verified in the held-out cohort, and in that situation results are reported per event, as pilot evidence. Whether the selector actually beats the baselines is treated as the empirical outcome, never as a precondition for reporting.")]),

 H1("5. Implementation"),
 figP("fig1_pipeline.png",640,200),
 P([T("The methodology is realized in a Python prototype, cart, organized by phase (manifest, events, oracles, labels, selectors, metrics, gates) with a CLI (manifest, events, ground-truth, select, evaluate, historical-run).")]),
 P([B("Two-layer environment. "),T("Reproducing historical regressions means building several different Qiskit revisions, which is incompatible with a single pinned Qiskit. We therefore separate a fixed harness layer (Python 3.11, Benchpress, and the oracle and measurement stack, all lockfile-pinned) from a Qiskit-under-test layer that is built from source for each event. Instrumentation is anchored on Qiskit 2.4.2 within the 2.x window. Building from source requires a Rust toolchain.")]),
 P([B("Per-event from-source runner. "),T("For historical events, a runner builds the baseline and candidate revisions into isolated virtual environments. In each environment a worker runs as a subprocess, transpiles the test units with its own Qiskit, and serializes the outputs (as QPY) together with the CPU timings. The harness then loads both sets of results back and applies the shared oracle pipeline. In this way the system under test stays isolated, while a single oracle implementation is reused for both revisions.")]),
 P([B("Reproducibility artifacts. "),T("Raw oracle evidence is written once and never overwritten, and the derived labels are regenerated from it so that they reproduce exactly, including the timing-dependent fields. The per-event environment recipes, the seeds, the pre-declared thresholds, the frozen stage map, and the frozen per-run configurations are all committed. The prototype also ships an automated test suite, with the six validity gates wired directly into evaluate.")]),
 P([B("What is implemented versus exercised in this pilot. "),T("To avoid over-stating coverage we separate three states.")]),
 BUL([B("Implemented and exercised in the primary results: "),T("the static manifest and instrumented profiling; the mutation engine (nine semantics-preserving quality operators); the tiered semantic oracle (exact ≤ 12 qubits, structural above); the quality Pareto oracle; the five baselines and the proposed risk_score selector; budgeted selection; the metric suite; the six validity gates; and the held-out evaluation on the nine-event × 32-unit (288-label) mutation cohort.")]),
 BUL([B("Implemented but not part of the primary results: "),T("the per-event from-source historical runner (used to attempt H1/H3/H4, which are respectively rejected, blocked, blocked); the targeted-trigger units and the Secondary retrospective evaluation; the exploratory performance Stage-1 screen; and the incomplete_basis_translation functional-fallback operator.")]),
 BUL([B("Specified but deferred (not implemented here): "),T("the sampled-statevector oracle tier (13–22 qubits); a property/layout (contract/metadata) oracle; a noisy-target determinism oracle; three-run-median performance on controlled hardware; performance Stage 2; and any learned selector.")]),

 H1("6. Evaluation"),
 P([T("We evaluate the three research questions on a micro corpus, on a single 16 GB laptop, anchored on Qiskit 2.4.2.")]),
 H2("6.1 Corpus and setup"),
 P([T("The corpus has fourteen change events (Table 4): nine controlled quality mutations on the 2.4.2 base and five historical Qiskit transpiler regressions identified from fix pull requests, each with exact candidate/baseline commit SHAs. To stay within a single 16 GB laptop the test corpus is width-capped at 8 qubits, enumerating 4 circuit families × 2 widths × 2 backend topologies × 2 optimization levels = 32 test units (Table 5); every unit lies within the exact-unitary oracle tier. The Primary CI evaluation runs on the verified mutation cohort, nine operators × 32 units = 288 (event, test) labels, because the five historical events require per-event from-source builds and are reported separately in the audit (Table 8). All nine operators have intended_mutation_target = quality; eight of the nine are detected by the black-box oracle on this corpus (only drop_vf2_post_layout is not), and because a quality-targeted mutation can still surface other observable labels for particular circuit–backend configurations we distinguish intended_mutation_target from observed_test_unit_label. The primary-CI eligibility rule (Section 4.8) is implemented and exercised synthetically on this mutation cohort; it is not yet validated on a real forward-regression event, because none is verified. Thresholds, seeds, and the stage map are pre-declared/frozen before evaluation, and no selector parameter was tuned on any event. Controlled mutation is an established way to construct faulty quantum-circuit benchmarks with varied, characterizable detectability [34], and our reporting, covering objects under test, baselines, setup, configuration, and artifact support, follows recent guidance on empirical quantum-software-testing studies [35].")]),
 cap("Table 4. Audited event ledger (cohorts never pooled)."),
 table([2950,1750,1900,2760],[
  ["Event(s)","Cohort","Fault type","Status"],
  ["9 mutation operators","mutation","quality","verified (pilot)"],
  ["H4 VF2PostLayout no-op (#14120)","forward_regression","performance","blocked (perf below screen)"],
  ["H1 ElidePermutations (#14603)","fix_boundary","semantic","rejected (production-unobservable)"],
  ["H3 VF2Layout determinism (#14730)","fix_boundary","quality","blocked (needs noisy target)"],
  ["H2 final_layout composition (#14919)","fix_boundary","semantic","blocked (not run)"],
  ["H5 VF2Layout panic (#16285)","fix_boundary","functional","blocked (not run)"],
 ]),
 sp(),
 cap("Table 5. Test corpus composition (32 units; width-capped at 8 qubits to keep compute low)."),
 table([3000,4360,2000],[
  ["Dimension","Values","Count"],
  ["Circuit family","GHZ, QFT, linear-QAOA, random-Clifford","4"],
  ["Width (qubits)","5, 8","2"],
  ["Backend topology","linear, heavy-hex","2"],
  ["Optimization level","1, 3","2"],
  ["Total units","","32"],
  ["Semantic oracle tier","exact-unitary (all widths ≤ 12)","32 units"],
 ]),
 sp(),
 cap("Table 6. Per-unit CPU-cost distribution across the 32 corpus units (mean cost per unit across the nine mutation events)."),
 table([4680,4680],[
  ["Statistic","Value (CPU seconds)"],
  ["minimum","0.00008"],
  ["median","0.0082"],
  ["mean","0.0515"],
  ["75th percentile","—"],
  ["maximum","0.3256"],
  ["coefficient of variation","1.85"],
  ["full-suite total","1.65"],
 ]),
 P([T("Because of the 8-qubit cap, the expensive 12-qubit line-topology units are excluded, so the suite stays cheap (at most 0.33 s per unit) while remaining moderately heterogeneous (CV ≈ 1.85). Broken down by width × backend, the mean per-unit cost ranges from 0.008 s for a 5-qubit unit to 0.17 s for an 8-qubit unit on the line topology. Cost variation is therefore present, but, as the results show, it is not the limiting factor. In absolute terms the entire 32-unit suite runs in roughly 1.65 CPU-seconds (median 0.0082 s per unit), so this pilot does not yet instantiate the cost-pressure regime that motivates cost-aware selection. That regime is exactly what the deferred scale-up targets, by adding expensive oracle tiers and events whose detecting tests are sparse or costly; until then, cheap detectors are abundant and almost any ordering succeeds early.")]),
 sp(),
 cap("Table 7. Mutation ledger: verified cohort (9 operators × 32 units = 288 labels). Best-selector event AUC; 8 of 9 operators are detected by the black-box oracle."),
 table([2700,1500,1100,1000,1000,1060],[
  ["Operator","Target stage","Fault type","Sem. kept","Detected?","Best AUC"],
  ["disable_optimization_loop","optimization","quality","yes","yes","0.98"],
  ["drop_vf2_post_layout","layout / opt","quality","yes","no","0.00"],
  ["downgrade_routing","routing","quality","yes","yes","1.00"],
  ["insert_redundant_cx_pair","optimization","quality","yes","yes","1.00"],
  ["drop_optimization_stage","optimization","quality","yes","yes","1.00"],
  ["force_opt_level_1","optimization","quality","yes","yes","1.00"],
  ["force_opt_level_0","optimization","quality","yes","yes","1.00"],
  ["downgrade_layout_trivial","layout","quality","yes","yes","1.00"],
  ["insert_redundant_x_pair","optimization","quality","yes","yes","1.00"],
 ]),
 sp(),
 cap("Table 8. Historical-event audit (5 events; none verified through black-box oracles in this pilot)."),
 table([1500,2300,2000,1100,2460],[
  ["ID (PR)","Fault type → channel","candidate→baseline (short SHA)","Status","Reason"],
  ["H1 (#14603)","semantic → contract/metadata","7c3890da→96fda188","rejected","built from source; corrupts virtual_permutation_layout, not the output unitary → production-unobservable"],
  ["H2 (#14919)","semantic → contract/metadata","14df5941→dfcc5c6c","not run","expected to share H1’s layout-property masking"],
  ["H3 (#14730)","quality → determinism","056c6413→d33ef533","blocked","non-determinism tied to a noisy Target absent from our coupling-map backend"],
  ["H4 (#14120)","performance → performance","a18e1516→a8d23667","blocked","overhead below the 20% Stage-1 screen; single-sample timing under-powered"],
  ["H5 (#16285)","functional → compilation_failure","f0fae6f3→0b2cdf2b","not run","input-specific crash; not yet reproduced"],
 ]),
 sp(),
 cap("Table 9. Controlled mutation operators and targeted regression triggers used in the pilot."),
 table([3000,1850,1750,2760],[
  ["Name","Kind","Stage / target","Effect / oracle"],
  ["disable_optimization_loop","mutation","optimization","remove peephole loop → residual redundancy (quality)"],
  ["drop_vf2_post_layout","mutation","layout/opt","omit VF2PostLayout → worse layout (quality)"],
  ["downgrade_routing","mutation","routing","force basic routing → more 2Q/depth (quality)"],
  ["insert_redundant_cx_pair","mutation","optimization","append CX–CX identity → +2 2Q gates (quality)"],
  ["drop_optimization_stage","mutation","optimization","disable the whole optimization stage (quality)"],
  ["force_opt_level_1","mutation","optimization","downgrade optimization level to 1 (quality)"],
  ["force_opt_level_0","mutation","optimization","downgrade optimization level to 0 (quality)"],
  ["downgrade_layout_trivial","mutation","layout","force trivial layout method (quality)"],
  ["insert_redundant_x_pair","mutation","optimization","append X–X identity → +2 1Q gates (quality)"],
  ["incomplete_basis_translation","mutation (fallback)","translation","drop 1q basis → TranspilerError (functional)"],
  ["trig-h1-elide-permutations","targeted (from fix)","ElidePermutations","PermutationGate+swaps; semantic oracle"],
  ["trig-h2-final-layout-composition","targeted (from fix)","routing final_layout","identity-after-routing; semantic oracle"],
  ["trig-h3-vf2-all-1q","targeted (from fix)","VF2Layout","all-1q; determinism (property) oracle"],
 ]),
 sp(),
 H2("6.2 RQ1: Feasibility and rigor"),
 P([T("The full pipeline runs from end to end. All six implementation-validity gates pass (Table 10), and the prototype passes 57 automated tests, among them the hand-computed metric checks and a leakage-invariance check. During validation we found and fixed two genuine defects: a CLI flag that silently dropped the targeted-run mode, and a semantic oracle that tried to materialize a 2^18 operator (about 512 GB) on an 18-qubit circuit, which is now capped and guarded by a regression test. We therefore answer RQ1 in the affirmative: the leakage-safe pipeline is operationally sound under the gate audit.")]),
 cap("Table 10. Implementation-validity gates."),
 table([6600,2760],[
  ["Gate","Result"],
  ["Budget compliance","PASS"],
  ["Reproducibility (same seed ⇒ same ranking)","PASS"],
  ["Leakage absence (current-event outcome cannot change ranking)","PASS"],
  ["Label reproducibility from raw artifacts","PASS"],
  ["Metric correctness vs hand-computed cases","PASS"],
  ["Oracle coverage","PASS"],
 ]),
 sp(),
 H2("6.3 RQ2: Selection effectiveness at pilot scale (a null result)"),
 P([T("On the verified mutation cohort (nine events, 32 units each), no selector improved on the simple deterministic baselines or on random ordering, the proposed risk_score included; in fact the proposed selector clearly trailed them (Tables 11–15, Figure 4). Diversity-only attains the best mean AUC at 0.886, the cost, history, and change-stage selectors tie at 0.877, random over 20 seeds reaches a median of 0.783 (with a seed range of 0.613–0.854), and the proposed selector is lowest at 0.692. This deficit is not merely noise. Against diversity-only the effect size is small and negative (Cliff’s δ = −0.30, Vargha–Delaney Â12 = 0.35), while against the cost baselines and random ordering it is negligible (|δ| ≤ 0.07).")]),
 P([T("The per-event view (Tables 12, 14) explains the aggregate. Eight of the nine mutations are detected, and most are detected at near-zero cost by every selector, so the real differentiator is whether a selector front-loads a cheap detecting unit. The proposed selector reaches the detector marginally earlier on six events, but it loses heavily on the two redundancy mutations (insert_redundant_cx_pair and insert_redundant_x_pair, with per-event AUC of 0.20 and 0.21) and on force_opt_level_1 (0.85): on these events its severity weighting promotes expensive, high-criticality units ahead of the cheap units that actually detect the fault. The ninth mutation, drop_vf2_post_layout, is undetected by every selector, because the black-box quality oracle does not register VF2PostLayout removal on this corpus, which caps every curve at 8/9 ≈ 0.889 (Figure 4).")]),
 P([T("The null result is not a consequence of uniform cost. The per-unit cost spans 8×10⁻⁵ s to 0.33 s (Table 6, CV ≈ 1.85), and yet the detecting units are cheap and plentiful: the eight detectable mutations are caught by many low-cost units, so every ordering reaches a detector within a small fraction of the suite budget, and detection stays essentially flat across the 5–40% budget fractions. Cost-aware prioritization simply cannot help once cheap detectors already saturate early detection.")]),
 P([T("We therefore report a null result at this scale. Across the nine events the proposed selector shows no advantage over the simple baselines or random ordering; the bootstrap confidence intervals are wide and overlapping (Table 15), and there is only a weak indication that its extra weighting hurts by deferring cheap detectors. In keeping with the claim-scope rule, and because zero forward-regression events are verified, we make no comparative-effectiveness or temporal-generalization claim.")]),
 P([T("All nine mutations share the Qiskit 2.4.2 base revision, so this is not a temporal-generalization test. The configured cutoff (2026-01-01) places all nine mutation split-groups on the test side, no mutation event is used for training, and the selector configurations are frozen (Table 3) and were not tuned on these events. We therefore describe the comparison as a frozen-configuration pilot rather than a held-out evaluation.")]),
 cap("Table 11. Frozen-configuration pilot metrics on the mutation cohort (9 events, 32 units each). Lower normalized TTFR and higher AUC are better; overhead is mean selection time."),
 table([2360,920,920,920,920,1000,1000,1320],[
  ["Selector","r@5%","@10%","@20%","@40%","nTTFR","AUC","overhead (s)"],
  ["diversity_only","0.89","0.89","0.89","0.89","0.114","0.886","0.0000"],
  ["cheapest_first","0.89","0.89","0.89","0.89","0.123","0.877","0.0000"],
  ["history_only","0.89","0.89","0.89","0.89","0.123","0.877","0.0003"],
  ["change_stage","0.89","0.89","0.89","0.89","0.123","0.877","0.0000"],
  ["random (median, 20 seeds) †","0.44","0.56","0.72","0.89","0.217","0.783","0.0000"],
  ["proposed (risk_score)","0.56","0.56","0.67","0.67","0.308","0.692","0.0017"],
 ]),
 new Paragraph({spacing:{after:80},children:[new TextRun({text:"† Random over 20 seeds: per-fraction detection medians 0.44 / 0.56 / 0.72 / 0.89 at 5 / 10 / 20 / 40%; mean AUC median 0.783 (seed range 0.613–0.854); mean norm. TTFR median 0.217 (range 0.146–0.387). The shaded band in Figure 4 shows the 20-seed min–max range.",size:18,italics:true})]}),
 cap("Table 12. Per-event area under the detection-vs-budget curve (1.0 = detected at ≈ zero cost; 0.0 = never detected). Nine mutation events."),
 table([2520,1140,1140,1100,1100,1140,1120],[
  ["Mutation event","cheap.","divers.","hist.","ch-stage","proposed","rand(med)"],
  ["disable_optimization_loop","0.97","0.98","0.97","0.97","0.99","0.88"],
  ["drop_vf2_post_layout","0.00","0.00","0.00","0.00","0.00","0.00"],
  ["downgrade_routing","0.98","1.00","0.98","0.98","1.00","0.94"],
  ["insert_redundant_cx_pair","1.00","1.00","1.00","1.00","0.20","0.99"],
  ["drop_optimization_stage","0.97","1.00","0.97","0.97","0.99","0.91"],
  ["force_opt_level_1","0.98","1.00","0.98","0.98","0.85","0.85"],
  ["force_opt_level_0","1.00","1.00","1.00","1.00","1.00","1.00"],
  ["downgrade_layout_trivial","1.00","1.00","1.00","1.00","1.00","1.00"],
  ["insert_redundant_x_pair","1.00","1.00","1.00","1.00","0.21","0.71"],
 ]),
 sp(),
 cap("Table 13. Win/tie/loss of the proposed selector vs each baseline, by per-event normalized TTFR (9 events)."),
 table([3000,2120,2120,2120],[
  ["Baseline","win","tie","loss"],
  ["cheapest_first","5","1","3"],
  ["diversity_only","3","1","5"],
  ["history_only","5","1","3"],
  ["change_stage","5","1","3"],
  ["random (median)","5","1","3"],
 ]),
 sp(),
 cap("Table 14. Per-event normalized TTFR by selector (lower is better); reconciles the win/tie/loss in Table 13. Nine mutation events."),
 table([2520,1140,1140,1100,1100,1140,1120],[
  ["Mutation event","cheap.","divers.","hist.","ch-stage","proposed","rand(med)"],
  ["disable_optimization_loop","0.033","0.017","0.033","0.033","0.009","0.120"],
  ["drop_vf2_post_layout","1.000","1.000","1.000","1.000","1.000","1.000"],
  ["downgrade_routing","0.021","0.004","0.021","0.021","0.001","0.063"],
  ["insert_redundant_cx_pair","0.001","0.001","0.001","0.001","0.804","0.008"],
  ["drop_optimization_stage","0.027","0.002","0.027","0.027","0.011","0.091"],
  ["force_opt_level_1","0.016","0.004","0.016","0.016","0.155","0.146"],
  ["force_opt_level_0","0.001","0.001","0.001","0.001","0.001","0.004"],
  ["downgrade_layout_trivial","0.002","0.001","0.002","0.002","0.001","0.004"],
  ["insert_redundant_x_pair","0.002","0.001","0.002","0.002","0.788","0.295"],
 ]),
 new Paragraph({spacing:{after:80},children:[new TextRun({text:"The proposed selector is marginally ahead on the six events whose cheapest detector it reaches marginally earlier, but loses heavily on insert_redundant_cx_pair (nTTFR 0.804) and insert_redundant_x_pair (0.788), where its severity (impact_prior) weighting defers a cheap detecting unit, and on force_opt_level_1 (0.155); drop_vf2_post_layout is an undetected tie. The few large losses pull the mean AUC below every baseline.",size:18,italics:true})]}),
 sp(),
cap("Table 15. Effect sizes (Cliff’s δ, Vargha–Delaney Â12; proposed vs each baseline on per-event AUC, 9 events) and bootstrap 95% CIs of mean AUC."),
 table([2400,1300,1500,1100,3060],[
  ["Comparison (proposed vs)","Cliff’s δ","magnitude","Â12","baseline mean AUC [95% CI]"],
  ["diversity_only","−0.30","small","0.35","0.886 [0.662, 0.998]"],
  ["cheapest_first","−0.05","negligible","0.475","0.877 [0.655, 0.993]"],
  ["history_only","−0.05","negligible","0.475","0.877 [0.655, 0.993]"],
  ["change_stage","−0.05","negligible","0.475","0.877 [0.655, 0.993]"],
  ["random (median)","+0.07","negligible","0.537","0.779 [0.750, 0.804]"],
 ]),
 new Paragraph({spacing:{after:80},children:[new TextRun({text:"Proposed selector mean AUC = 0.692 [0.400, 0.912]. Effect sizes are negligible against the cost baselines and random, and small-but-negative against diversity-only; the wide, overlapping CIs at nine events support a claim of no advantage rather than a reliable deficit.",size:18,italics:true})]}),
 sp(),
 H2("6.4 Ablation and sensitivity of risk_score"),
 P([T("To locate the source of the deficit, we ablated each risk_score component over the cached labels, with no re-transpilation (Table 16). Removing the severity term impact_prior raises the mean AUC from 0.692 to 0.716, so this term is actively harmful: a high impact_prior on expensive, high-criticality units defers the cheap units that detect these faults. The novelty term helps only marginally, since the AUC falls to 0.688 without it, while change_stage_match and oracle_confidence are inert on this corpus, because every unit shares the modified stage and the same exact-unitary oracle tier. A sensitivity sweep over the ε floor ({0.01, 0.05, 0.10}) and the exploration reserve ({10, 15, 20}%) leaves the mean AUC unchanged at 0.692, which tells us the result is robust and not a tuning artifact.")]),
 cap("Table 16. Ablation of risk_score components (mutation cohort, 9 events; reuses cached labels, no transpilation)."),
 table([3400,1980,1980,2000],[
  ["risk_score variant","mean AUC","mean nTTFR","recall@20%"],
  ["full","0.692","0.308","0.667"],
  ["− novelty","0.688","0.312","0.667"],
  ["− change_stage","0.692","0.308","0.667"],
  ["− oracle_confidence","0.692","0.308","0.667"],
  ["− impact_prior","0.716","0.284","0.667"],
 ]),
 sp(),
 figP("fig4_detection.png",470,250),
 P([T("Figure 4 plots the detection-vs-budget curves. Diversity-only and the cost, history, and change-stage baselines reach the 8/9 ≈ 0.889 ceiling almost immediately, random (the median) climbs more gradually, and the proposed selector plateaus lower because it defers cheap detectors on three events. The shaded band shows the 20-seed min–max range for random ordering.")]),
 H2("6.5 RQ3: Observability of historical regressions"),
 P([T("We attempted five historical events, and we must separate a demonstrated observability gap from cases that are merely unreproduced or under-powered at this scale. Of the five, one (H1) is a built-from-source demonstration that a real regression is invisible to a black-box output oracle. The remaining four are inconclusive, and they are not evidence that the oracles under-detect.")]),
 BUL([B("H1 (ElidePermutations, #14603): demonstrated observability gap. "),T("Both revisions were built from source. The fault belongs to the transpiler_contract_or_metadata channel: it corrupts the virtual_permutation_layout property while leaving the layout-applied output unitary correct. As a result, the output-only semantic oracle reports equivalence on the buggy build, even when the fix’s own regression circuit is run through the full preset pass manager. Under the production-pipeline rule the event is therefore rejected as real but production-unobservable. This is the single place where the pilot establishes that a black-box output oracle misses a contract/metadata-channel fault, and Appendix A gives the minimal trigger, the exact SHAs and the corrupted field, the oracle outcome, and the reproduction command.")]),
 BUL([B("H3 (VF2Layout non-determinism, #14730): inconclusive (not reproduced). "),T("The determinism-channel fault reproduces only under a noisy device target absent from our coupling-map backend; a strengthened, layout-sensitive determinism oracle observed determinism on our circuit. We cannot conclude anything about oracle sensitivity because the triggering condition was never created. Blocked. This is consistent with a large dynamic study that executed the Qiskit Terra suite 10,000 times across 23 releases and found genuine flakiness rare but often requiring thousands of runs to detect reliably, well beyond a typical CI budget [36].")]),
 BUL([B("H4 (VF2PostLayout no-op, #14120): inconclusive (under-powered). "),T("The redundant-pass overhead stays below the 20% Stage-1 screen under single-sample timing; this is a measurement-power limitation, not a demonstrated blind spot. Deferred to a controlled-hardware, multi-run protocol.")]),
 BUL([B("H2 (#14919) and H5 (#16285): not run. "),T("H2 is expected to share H1’s layout-property masking and H5 is an input-specific crash; neither has been reproduced, so neither contributes evidence.")]),
 P([T("The controlled mutation cohort, by contrast, labels reliably (Table 7). We therefore answer RQ3 narrowly. The pilot demonstrates a single concrete observability gap, namely a contract/metadata-channel regression (H1) that is invisible to black-box output oracles, and it leaves the determinism and small-overhead channels open, since we could not reproduce or adequately power them on commodity hardware. We do not claim that black-box oracles broadly under-detect. What we claim is narrower: at least one important manifestation channel is unobservable to them, and the others remain untested here. Section 6.6 then quantifies how often such channels occur among real transpiler fixes.")]),

 H2("6.6 Observability of real transpiler regressions: a repository-mining study"),
 P([T("The H1 result raises a question that the pilot cannot answer on its own: how common are output-invisible regressions in practice? To estimate this, we mined the merged, changelog-listed bug-fix pull requests labelled mod: transpiler in the Qiskit repository and classified each one by the manifestation channel of the fault it fixes (Section 2.2). This follows repository-mining practice for quantum-software bug characterization [37] and the empirical-reporting guidance for quantum-software testing [35]. Two authors independently classified the 26 fixes from their titles, descriptions, and linked issues, using a written codebook and recording a confidence flag for each. Agreement was substantial: Cohen's κ = 0.68 on the binary observable-by-output-oracle judgment (84.6% raw agreement) and κ = 0.67 on the seven-class channel (73.1%), and both raters independently identified 10 of the 26 fixes as output-invisible. The four binary disagreements were resolved by discussion; in particular the ElidePermutations case (PR #14603, our H1) was adjudicated as output-invisible on the strength of direct built-from-source evidence. The codebook, both raters' labels, and the confidence flags are released with the artifact. As Table 17 shows, 10 of the 26 fixes (38%, or 41% once low-confidence cases are excluded) fall in channels that a black-box output-equivalence oracle cannot observe: corrupted layout or permutation contract metadata (7), non-determinism (2), and a dropped global phase (1, which is invisible to equivalence-modulo-global-phase checks). The built-from-source H1 case is one instance of the largest of these classes. The observability gap is therefore not an isolated curiosity. A substantial minority of real transpiler regressions are unobservable to output-only oracles, which motivates treating fault-class-matched oracles, such as property and layout comparison and determinism checks, as first-class CI checks.")]),
 cap("Table 17. Manifestation channels of 26 mined Qiskit transpiler bug-fixes. \u201cObservable\u201d = detectable by a black-box output-equivalence oracle."),
 table([3200,1200,2200,2760],[
  ["Manifestation channel","Count","Observable?","Example PRs"],
  ["output_semantic","5","yes","#16428, #16337, #13670"],
  ["compilation_failure","6","yes","#15626, #16285, #14998"],
  ["circuit_quality","4","yes","#14667, #13884"],
  ["performance","1","yes (if over screen)","#14120"],
  ["contract / metadata","7","no","#14939, #14919, #13945, #13833, #14603"],
  ["determinism / reproducibility","2","no","#14763, #14730"],
  ["global phase","1","no","#15943"],
 ]),
 new Paragraph({spacing:{after:120},children:[new TextRun({text:"Threats: classification is title-and-description based, a construct-validity threat that we mitigate by independent double-coding (two authors; Cohen's κ = 0.68 on the binary observability judgment and 0.67 on the channel) and by releasing the codebook, both raters' labels, and the confidence flags for re-coding; the sample is recent merged fixes, not a complete census, so the percentages are indicative rather than population estimates.",size:18,italics:true})]}),
 sp(),
 H1("7. Discussion"),
 P([T("The central lesson of the pilot is methodological rather than a horse-race outcome. Its most concrete empirical finding is an observability gap. A real transpiler regression, H1, lives in the transpiler_contract_or_metadata channel: its layout metadata is incorrect, yet the output unitary it produces is intact, and so a black-box output oracle cannot see it. We are careful not to over-generalize from a single event. The determinism and small-overhead channels (H3 and H4) remain open in our data because we could not reproduce or adequately power them, not because we watched the oracles fail. The honest reading is therefore a caution rather than a sweeping claim: equivalence checking of compiled outputs is provably insufficient for at least one important class of compiler regression, and the contract/metadata, determinism, and performance channels each plausibly need an oracle of their own. The repository-mining study of §6.6 shows that these output-invisible channels account for roughly 38% of recent real transpiler bug-fixes, which makes the gap quantitatively material rather than anecdotal. The methodology already encodes the design consequences: a controlled mutation cohort serves as a reliable labelling backbone; test provenance is accounted for strictly, since a post-fix test can show that a fault is real (a Secondary claim) but cannot prove that a selector would have caught it in real CI; and fault-class-matched oracles are planned for the scale-up.")]),
 P([T("The selection result is a null result, and we treat it as informative rather than disappointing. At this scale the transparent risk_score selector did not beat the simple cost, diversity, history, and change-stage baselines, nor random ordering, and it trailed them because its severity weighting can defer a cheap detecting test (§6.3). An ablation isolates the cause: once the severity term (impact_prior) is removed, the AUC returns to baseline level (Table 16), so the design is not wrong in principle but is mis-calibrated for a regime in which detection cost and fault severity are decoupled. More broadly, no method manages to separate, because the detecting units are cheap and plentiful, detection saturates within a small fraction of the suite budget, and there is almost no budget regime in which ordering can matter. Whether the extra structure in risk_score helps is therefore still an open question, one that only a larger, cost-heterogeneous corpus with verified forward regressions can settle, and the claim-scope rule correctly forbids any comparative-effectiveness claim from these nine events. The most natural next prototype simply drops the impact_prior term, which on its own recovers baseline-level AUC (Table 16); we offer this as a lesson rather than a result, since it is a post-hoc adjustment evaluated on the very same nine events.")]),

 H1("8. Threats to Validity"),
 P([B("Construct. "),T("The largest threat is oracle observability (§7). A black-box oracle can miss contract/metadata-channel faults, as we demonstrate for H1, and it may also miss determinism- and performance-channel faults, which we did not test here, so a “pass” does not certify that a circuit is fault-free. We mitigate this by separating the cohorts, by using an empirical, confirmation-based false-positive rate, and by recording which oracle tier produced each label and which manifestation channel each historical fault occupies. The provenance rule also prevents post-fix tests from inflating the Primary claim.")]),
 P([B("Internal. "),T("Timing on a single laptop is noisy, so we calibrate cost with CPU process time, treat performance as exploratory, and exclude high-load runs. Write-once raw artifacts, fixed seeds, and labels regenerated from the raw evidence all support reproducibility. Test non-determinism is a known confound in regression testing [38]. We therefore treat determinism and reproducibility as their own manifestation channel rather than folding them into correctness, and, consistent with the evidence that flaky tests are most detectable when newly added [39], we confine post-fix targeted triggers to the Secondary evaluation.")]),
 P([B("External. "),T("The corpus is small and specific to the Qiskit 2.x transpiler, so the results are pilot-scoped and must not be generalized without the planned scale-up. The verified events are all quality mutations, which may not represent the full fault distribution. There is also a scope limitation in the evaluation itself: the primary results exercise only the exact-unitary and quality-oracle tiers, whereas the property and layout, sampled-statevector, noisy-target determinism, and robust performance oracles are described in the methodology but deferred. The evaluated system is therefore narrower than the oracle architecture we discuss, and closing that gap is a central part of the scale-up.")]),
 P([B("Conclusion. "),T("With so few events, statistical comparison is under-powered. We therefore avoid significance claims, report per-event outcomes alongside the averages, and bind comparative claims with the rule that requires at least three forward-regression events. The leakage-absence gate guards against optimistic bias. The null selection result is itself a per-event finding, not a powered comparison.")]),

 H1("9. Limitations and Future Work"),
 P([T("To summarize, the study is a feasibility pilot: zero historical events are verified through the production oracles, the verified cohort is mutation-only, and the selector comparison yields a null result. At this scale the proposed selector showed no advantage over the simple baselines or random ordering, and because the detecting units are cheap and plentiful, detection saturates at a tiny budget fraction, which leaves almost no regime in which cost-aware ordering can separate the methods (despite the high overall cost variance reported in Table 6). The deferred scale-up will do four things. First, it will expand the corpus toward at least three verified forward-regression events, and will deliberately include events whose detecting tests are expensive or sparse, so that cost-aware ordering finally has a regime in which to separate methods; the present corpus fails to discriminate because cheap detectors dominate, not because the costs are uniform. Second, it will add fault-class-matched oracles: a property and layout oracle comparing TranspileLayout and routing_permutation, a noisy-target determinism oracle, and three-run-median performance on controlled hardware, all in a clearly labelled retrospective track. Third, it will introduce an optional comparison against logistic-regression and gradient-boosted-tree selectors under identical anti-leakage rules. Fourth, it will trace selected fix-boundary events back to their true introducing commits through bisection, converting them into the forward cohort. Only once at least three forward-regression events are verified do comparative-effectiveness claims about temporal generalization become admissible.")]),

 H1("10. Conclusion"),
 P([T("In this paper we asked whether regression-test selection and prioritization, long established for classical software, can be realized for the quantum transpiler in a leakage-safe and cost-aware manner, and what such an approach achieves at feasibility scale. We designed a methodology that separates change events into non-pooled cohorts, applies tiered layout-aware oracles with an empirical false-positive rate, scores tests with a transparent selector that distinguishes fault severity from detection confidence, and is guarded by six implementation-validity gates and a strict claim-scope rule. We then realized the methodology in an open prototype and evaluated it on a Qiskit 2.x micro corpus.")]),
 P([T("We report our empirical findings without embellishment. Across nine controlled mutations, the transparent selector did not outperform the simple cost, diversity, history, and change-stage baselines, nor random ordering. A per-unit cost analysis explains why: the test units that detect the injected faults are cheap and plentiful, so detection saturates within a small fraction of the budget no matter how the tests are ordered, and an ablation pinpoints the selector's severity term as the component responsible, which rules out a mere tuning issue. Separately, our attempt to reproduce five real historical regressions from source produced one clear positive finding, namely an ElidePermutations regression whose corrupted internal layout metadata is invisible to output-equivalence oracles. The remaining cases could not be reproduced or adequately powered on commodity hardware, and we report them as inconclusive rather than as evidence of oracle weakness.")]),
 P([T("Taken together, the study contributes a rigorous and reproducible evaluation methodology, an honest feasibility baseline against which future selectors can be compared, and a concrete demonstration that equivalence checking of compiled outputs is insufficient to observe an important class of transpiler-contract faults. None of these outcomes amounts to a comparative-effectiveness claim. What they do provide is a credible foundation, together with a pre-specified path toward a larger empirical evaluation that uses verified forward regressions, cost-heterogeneous corpora, and fault-class-matched oracles.")]),

 H1("11. Artifact Availability"),
 P([T("To support review and reproduction, the artifact is archived at https://doi.org/10.5281/zenodo.21020113 and the public repository is https://github.com/furqan-nr/QIP-Submission, containing: the prototype (cart) and CLI; the automated test suite and six validity gates; the static manifest and mutation engine; the event ledger with exact candidate/baseline commit SHAs; the frozen change–stage map, pre-declared thresholds, RNG seeds, and the frozen risk_score configuration (Table 3); a pinned environment lock (requirements.lock); the write-once raw oracle artifacts and derived labels; the generated evaluation.json; the repository-mining dataset (data/observability_mining.csv); and an OSI-approved open-source license.")]),
 P([T("The frozen-configuration pilot of Section 6 is reproduced exactly by two commands:")]),
 new Paragraph({spacing:{after:40},alignment:AlignmentType.LEFT,children:[M("python -m cart.cli ground-truth --unit-limit 64")]}),
 new Paragraph({spacing:{after:120},alignment:AlignmentType.LEFT,children:[M("python -m cart.cli evaluate --split all --random-seeds 20")]}),
 P([T("These write Tables 11–14, the per-fraction random aggregates, the cost-distribution summary, and the detection-vs-budget data of Figure 4 to a single evaluation.json. Building the historical events (e.g., H1) additionally requires a Rust toolchain to compile the per-event Qiskit revisions from source; the per-event recipe and reproduction command are given in Appendix A.")]),

 H1("Statements and Declarations"),
 P([B("Funding. "),T("The authors received no specific grant from any funding agency, commercial, or not-for-profit sector for this work.")]),
 P([B("Competing Interests. "),T("The authors declare no competing financial or non-financial interests.")]),
 P([B("Data Availability. "),T("All data supporting the results, namely the change-event ledger, the write-once raw oracle artifacts, the derived labels, and the generated evaluation reports, are available in the public repository (https://github.com/furqan-nr/QIP-Submission) and archived at https://doi.org/10.5281/zenodo.21020113; see Section 11.")]),
 P([B("Code Availability. "),T("The cart prototype, its command-line interface, and the build scripts are available in the public repository (https://github.com/furqan-nr/QIP-Submission, archived at https://doi.org/10.5281/zenodo.21020113) under the MIT open-source license; see Section 11.")]),
 P([B("Author Contributions. "),T("F. Nasir conceived the study, implemented the prototype, conducted the evaluation, and wrote the manuscript. A. Shah supervised the work and contributed to the study design and the critical revision of the manuscript. I. Alam contributed to the methodology and the analysis and reviewed the manuscript. All authors read and approved the final manuscript.")]),
 P([B("Ethics Approval and Consent. "),T("Not applicable; the study involves no human or animal subjects.")]),
 P([B("Use of AI Tools. "),T("AI-based assistants were used to support manuscript drafting and software implementation under the authors' supervision; the authors verified all results and take full responsibility for the content.")]),
 H1("Appendix A. Direct evidence for H1 (ElidePermutations, PR #14603)"),
 P([T("H1 is the pilot’s one demonstrated observability gap, so we record its evidence explicitly.")]),
 BUL([B("Revisions (built from source). "),T("Candidate (buggy) 7c3890da097c851876b86453a1da6ee7d3208048 → baseline (fixed) 96fda18888de4492f37ccdb93faf15dc014c99eb; fix-boundary differential, PR #14603, fix-commit dated 2025-06-16.")]),
 BUL([B("Minimal trigger. "),T("A circuit containing a PermutationGate together with two-qubit gates (the unit trig-h1-elide-permutations, drawn from the fix’s own regression test), transpiled through the full preset pass manager at optimization level 3 on backends none and line.")]),
 BUL([B("Corrupted field. "),T("The buggy ElidePermutations pass corrupts the virtual_permutation_layout property recorded in the TranspileLayout / output metadata; the layout-applied output unitary is left correct.")]),
 BUL([B("Oracle outcome. "),T("The layout-normalized exact-unitary oracle reports EQUIVALENT (pass) on the buggy candidate, identical to the baseline result, on both backends. The output-only oracle therefore cannot distinguish buggy from fixed; the fault is only visible by comparing the recorded permutation property directly (a contract/metadata check the production pipeline does not run). Per the production-pipeline rule the event is rejected, not credited.")]),
 BUL([B("Reproduction. "),T("Build both revisions with the per-event from-source runner, then run:")]),
 new Paragraph({spacing:{after:120},alignment:AlignmentType.LEFT,children:[M("python -m cart.cli historical-run --event hist-elide-permutations-mapping --use-targeted")]}),
 P([T("The recorded per-run property values (baseline vs candidate virtual_permutation_layout) are written to the event’s write-once raw artifact and are included in the deposited archive (Section 11).")]),

 H1("References"),
REF('[1] Paltenghi M, Pradel M (2022) Bugs in quantum computing platforms: an empirical study. Proc ACM Program Lang (OOPSLA). arXiv:2110.14560'),
REF('[2] Nation PD et al (2024) Benchmarking the performance of quantum computing software for quantum circuit creation, manipulation and compilation. Nat Comput Sci'),
REF('[3] Yoo S, Harman M (2012) Regression testing minimization, selection and prioritisation: a survey. Softw Test Verif Reliab 22(2):67–120'),
REF('[4] Machalica M, Samylkin A, Porth M, Chandra S (2019) Predictive test selection. In: Proc ICSE-SEIP. arXiv:1810.05286'),
REF('[5] Paltenghi M, Pradel M (2023) MorphQ: metamorphic testing of the Qiskit quantum computing platform. In: Proc ICSE. doi:10.1109/ICSE48619.2023.00202'),
REF('[6] Kitt L et al (2024) MorphQ++: a reproducibility study of metamorphic testing on quantum compilers. In: Proc IEEE/ACM ASE Workshops. doi:10.1145/3695750.3695823'),
REF('[7] Pontolillo G et al (2025) QuCheck: a property-based testing framework for quantum programs in Qiskit. arXiv:2503.22641'),
REF('[8] Luo J et al (2026) QEMI: a quantum software stacks testing framework via equivalence modulo inputs. arXiv preprint'),
REF('[9] Javadi-Abhari A, Treinish M, Krsulich K et al (2024) Quantum computing with Qiskit. arXiv:2405.08810'),
REF('[10] Paltenghi M, Pradel M (2024a) A survey on testing and analysis of quantum software. arXiv:2410.00650'),
REF('[11] Barr ET, Harman M, McMinn P, Shahbaz M, Yoo S (2015) The oracle problem in software testing: a survey. IEEE Trans Softw Eng 41(5):507–525'),
REF('[12] Burgholzer L, Wille R (2021) Advanced equivalence checking for quantum circuits. IEEE Trans Comput-Aided Des Integr Circuits Syst 40(9):1810–1824'),
REF('[13] Elbaum S, Malishevsky AG, Rothermel G (2002) Test case prioritization: a family of empirical studies. IEEE Trans Softw Eng 28(2):159–182'),
REF('[14] Elbaum S, Malishevsky A, Rothermel G (2001) Incorporating varying test costs and fault severities into test case prioritization. In: Proc ICSE'),
REF('[15] Rothermel G, Untch RH, Chu C, Harrold MJ (2001) Prioritizing test cases for regression testing. IEEE Trans Softw Eng 27(10):929–948'),
REF('[16] Elbaum S, Rothermel G, Penix J (2014) Techniques for improving regression testing in continuous integration development environments. In: Proc ACM SIGSOFT FSE, pp 235–245'),
REF('[17] Elsner D, Hauer F, Pretschner A, Reimer S (2021) Empirically evaluating readily available information for regression test optimization in continuous integration. In: Proc ACM SIGSOFT ISSTA, pp 491–504'),
REF('[18] Peng Q, Shi A, Zhang L (2020) Empirically revisiting and enhancing IR-based test-case prioritization. In: Proc ACM SIGSOFT ISSTA, pp 324–336'),
REF('[19] Spieker H, Gotlieb A, Marijan D, Mossige M (2017) Reinforcement learning for automatic test case prioritization and selection in continuous integration. In: Proc ACM SIGSOFT ISSTA, pp 12–22'),
REF('[20] Prado Lima JA, Vergilio SR (2022) A multi-armed bandit approach for test case prioritization in continuous integration environments. IEEE Trans Softw Eng 48(2):453–465'),
REF('[21] Pan R, Bagherzadeh M, Ghaleb TA, Briand L (2022) Test case selection and prioritization using machine learning: a systematic literature review. Empir Softw Eng 27(2):29'),
REF('[22] Aparicio-Morales A, Moguel E, Garcia-Alonso J, Murillo JM (2024) An overview of quantum software engineering in Latin America. Quantum Inf Process 23'),
REF('[23] Huang Y et al (2024) Qubit mapping: the adaptive divide-and-conquer approach. Quantum Inf Process 23'),
REF('[24] Wang J, Zhang Q, Xu GH, Kim M (2021) QDiff: differential testing of quantum software stacks. In: Proc IEEE/ACM ASE, pp 692–704'),
REF('[25] Ye J et al (2026) QSPE: enumerating skeletal quantum programs for quantum library testing. arXiv preprint'),
REF('[26] Choudhury N et al (2025) Concolic testing for quantum compilers. In: Proc IEEE ICCD'),
REF('[27] Tao R, Shi Y, Yao J, Li X, Javadi-Abhari A, Cross AW, Chong FT, Gu R (2022) Giallar: push-button verification for the Qiskit quantum compiler. In: Proc ACM SIGPLAN PLDI, pp 641–656'),
REF('[28] Paltenghi M, Pradel M (2024b) Analyzing quantum programs with LintQ: a static analysis framework for Qiskit. Proc ACM Softw Eng 1(FSE):1135–1157'),
REF('[29] Zhao P, Zhao J, Miao Z, Lan S (2023) Bugs4Q: a benchmark of existing bugs to enable controlled testing and debugging studies for quantum programs. J Syst Softw 205:111805'),
REF('[30] Mendiluze E, Ali S, Yue T, Arcaini P (2021) Muskit: a mutation analysis tool for quantum software testing. In: Proc IEEE/ACM ASE'),
REF('[31] Fortunato D, Campos J, Abreu R (2022) Mutation testing of quantum programs: a case study with Qiskit. IEEE Trans Quantum Eng 3:1–17'),
REF('[32] Ramalho NCL et al (2024) Testing and debugging quantum programs: the road to 2030. ACM Trans Softw Eng Methodol'),
REF('[33] Wojciechowski K et al (2026) Open QBench: a benchmarking framework for evaluating quantum computing platforms. Quantum Inf Process'),
REF('[34] Mendiluze Usandizaga E, Yue T, Arcaini P, Ali S (2023) Quantum circuit mutants: empirical analysis and recommendations. Empir Softw Eng 28:6'),
REF('[35] Li Y et al (2026) A methodological analysis of empirical studies in quantum software testing. arXiv preprint'),
REF('[36] Kim D et al (2025) Detecting flakiness in quantum software: a dynamic testing approach. Preprint (venue/DOI to be confirmed)'),
REF('[37] Yousuf MM et al. (2025) Characterizing bugs and quality attributes in quantum software: a large-scale empirical study. arXiv preprint.'),
REF('[38] Luo Q, Hariri F, Eloussi L, Marinov D (2014) An empirical analysis of flaky tests. In: Proc ACM SIGSOFT FSE, pp 643–653'),
REF('[39] Lam W, Winter S, Wei A, Xie T, Marinov D, Bell J (2020) A large-scale longitudinal study of flaky tests. Proc ACM Program Lang 4(OOPSLA):1–29'),
];

const doc=new Document({creator:"cart",
 styles:{default:{document:{run:{font:F,size:21}}},paragraphStyles:[
  {id:"Title",name:"Title",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:34,bold:true,font:F},paragraph:{spacing:{after:120},alignment:AlignmentType.CENTER}},
  {id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:27,bold:true,font:F},paragraph:{spacing:{before:240,after:120},outlineLevel:0}},
  {id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:23,bold:true,font:F},paragraph:{spacing:{before:160,after:90},outlineLevel:1}},
 ]},
 numbering:{config:[
  {reference:"bul",levels:[{level:0,format:LevelFormat.BULLET,text:"•",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:540,hanging:270}}}}]},
  {reference:"num",levels:[{level:0,format:LevelFormat.DECIMAL,text:"%1.",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:540,hanging:300}}}}]},
  {reference:"refs",levels:[{level:0,format:LevelFormat.DECIMAL,text:"[%1]",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:600,hanging:400}}}}]},
 ]},
 sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,right:1440,bottom:1440,left:1440}}},
  footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"Leakage-Safe Evaluation of Qiskit Transpiler Regression Testing (Quantum Information Processing)  ·  p. ",size:18}),new TextRun({children:[PageNumber.CURRENT],size:18})]})]})},
  children:kids}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("PAPER.docx",b);console.log("wrote",b.length,"bytes");});
